// Analyst Agent V1 — adversarial investigator for ideas/.
// Usage: npm run analyst   (requires ANTHROPIC_API_KEY)
import Anthropic from "@anthropic-ai/sdk";
import fs from "node:fs";
import path from "node:path";
import { ANALYST_SYSTEM_PROMPT } from "./prompt.js";
import {
  type AnalysisEntry,
  extractVerdict,
  findIdeaFiles,
  ideaNameFromFile,
  reportRelativePath,
  updateProjectStatus,
} from "./lib.js";

const ROOT = process.cwd();
const IDEAS_DIR = path.join(ROOT, "ideas");
const EXPERIMENTS_DIR = path.join(ROOT, "experiments");
const STATUS_FILE = path.join(ROOT, "PROJECT_STATUS.md");
const MODEL = "claude-opus-4-8";

async function analyzeIdea(
  client: Anthropic,
  name: string,
  ideaText: string,
): Promise<string> {
  const stream = client.messages.stream({
    model: MODEL,
    max_tokens: 64000,
    thinking: { type: "adaptive" },
    system: ANALYST_SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Investigate the following startup idea. The idea file is named "${name}".\n\n---\n\n${ideaText}`,
      },
    ],
  });

  // Lightweight progress indicator while the (long) report streams in.
  let chars = 0;
  stream.on("text", (delta) => {
    chars += delta.length;
    if (chars > 2000) {
      process.stdout.write(".");
      chars = 0;
    }
  });

  const message = await stream.finalMessage();
  return message.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

function reportHeader(name: string, sourceFile: string): string {
  return [
    `<!-- Generated by the Analyst agent on ${new Date().toISOString()} -->`,
    `<!-- Source: ideas/${path.basename(sourceFile)} | Model: ${MODEL} -->`,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const ideaFiles = findIdeaFiles(IDEAS_DIR);
  if (ideaFiles.length === 0) {
    console.log("No idea files found in ideas/ (README.md is ignored).");
    console.log("Add one markdown file per idea, then run `npm run analyst` again.");
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ANTHROPIC_API_KEY is not set. Get a key at https://platform.claude.com/");
    process.exitCode = 1;
    return;
  }

  const client = new Anthropic();
  fs.mkdirSync(EXPERIMENTS_DIR, { recursive: true });

  console.log(`Analyst: ${ideaFiles.length} idea(s) to investigate.\n`);
  const entries: AnalysisEntry[] = [];

  for (const file of ideaFiles) {
    const name = ideaNameFromFile(file);
    const ideaText = fs.readFileSync(file, "utf8");
    process.stdout.write(`Investigating "${name}" `);

    try {
      const report = await analyzeIdea(client, name, ideaText);
      const verdict = extractVerdict(report);
      const outPath = path.join(EXPERIMENTS_DIR, `${name}-analysis.md`);
      fs.writeFileSync(outPath, reportHeader(name, file) + report + "\n");
      entries.push({ name, verdict, reportPath: reportRelativePath(name) });
      console.log(` done → ${verdict} (${reportRelativePath(name)})`);
    } catch (err) {
      if (err instanceof Anthropic.APIError) {
        console.error(`\nAPI error ${err.status} on "${name}": ${err.message}`);
      } else {
        console.error(`\nFailed on "${name}":`, err);
      }
      process.exitCode = 1;
    }
  }

  if (entries.length > 0) {
    const existing = fs.existsSync(STATUS_FILE)
      ? fs.readFileSync(STATUS_FILE, "utf8")
      : "# Project Status\n";
    const today = new Date().toISOString().slice(0, 10);
    fs.writeFileSync(STATUS_FILE, updateProjectStatus(existing, entries, today));
    console.log(`\nPROJECT_STATUS.md updated (${entries.length} analysis entries).`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
