// Analyst Agent V2 — adversarial investigator for ideas/, with a lessons
// system: it reads LESSONS.md before analyzing, applies prior lessons, and
// appends new generalizable lessons after every analysis so the factory
// gets smarter with each idea.
// Usage: npm run analyst   (requires ANTHROPIC_API_KEY)
import Anthropic from "@anthropic-ai/sdk";
import fs from "node:fs";
import path from "node:path";
import { ANALYST_SYSTEM_PROMPT } from "./prompt.js";
import {
  type AnalysisEntry,
  extractVerdict,
  findAnalysisFiles,
  findIdeaFiles,
  ideaNameFromAnalysisFile,
  ideaNameFromFile,
  reportRelativePath,
  updateProjectStatus,
} from "./lib.js";
import {
  extractCandidateLessons,
  extractRecommendations,
  parseLessons,
  renderKnowledgeBase,
  updateLessonsFile,
} from "./lessons.js";

const ROOT = process.cwd();
const IDEAS_DIR = path.join(ROOT, "ideas");
const EXPERIMENTS_DIR = path.join(ROOT, "experiments");
const STATUS_FILE = path.join(ROOT, "PROJECT_STATUS.md");
const LESSONS_FILE = path.join(ROOT, "LESSONS.md");
const RECOMMENDATIONS_FILE = path.join(ROOT, "agents", "analyst", "RECOMMENDATIONS.md");
const MODEL = "claude-opus-4-8";

function buildUserMessage(
  name: string,
  ideaText: string,
  knowledgeBase: string,
  priorAnalyses: string,
): string {
  return [
    `Investigate the following startup idea. The idea file is named "${name}".`,
    "",
    "## Prior lessons knowledge base (from LESSONS.md)",
    "",
    knowledgeBase,
    "",
    "## Previous analyses by this Analyst (for Section 10 — Repeated Risks)",
    "",
    priorAnalyses,
    "",
    "## The idea",
    "",
    "---",
    "",
    ideaText,
  ].join("\n");
}

/** Summarize prior reports (name → verdict) for the repeated-risks section. */
function summarizePriorAnalyses(excludeName: string): string {
  const lines = findAnalysisFiles(EXPERIMENTS_DIR)
    .filter((f) => ideaNameFromAnalysisFile(f) !== excludeName)
    .map((f) => {
      const verdict = extractVerdict(fs.readFileSync(f, "utf8"));
      return `- ${ideaNameFromAnalysisFile(f)}: ${verdict}`;
    });
  return lines.length > 0 ? lines.join("\n") : "(none yet — this is the first analysis)";
}

async function analyzeIdea(
  client: Anthropic,
  userMessage: string,
): Promise<string> {
  const stream = client.messages.stream({
    model: MODEL,
    max_tokens: 64000,
    thinking: { type: "adaptive" },
    system: ANALYST_SYSTEM_PROMPT,
    messages: [{ role: "user", content: userMessage }],
  });

  // Lightweight progress indicator while the (long) report streams in.
  let chars = 0;
  stream.on("text", (delta) => {
    chars += delta.length;
    if (chars > 2000) {
      process.stdout.write(".");
      chars = 0;
    }
  });

  const message = await stream.finalMessage();
  return message.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

function reportHeader(sourceFile: string): string {
  return [
    `<!-- Generated by the Analyst agent (V2) on ${new Date().toISOString()} -->`,
    `<!-- Source: ideas/${path.basename(sourceFile)} | Model: ${MODEL} -->`,
    "",
  ].join("\n");
}

function appendRecommendations(
  recommendations: { idea: string; text: string }[],
  date: string,
): void {
  if (recommendations.length === 0) return;
  const existing = fs.existsSync(RECOMMENDATIONS_FILE)
    ? fs.readFileSync(RECOMMENDATIONS_FILE, "utf8")
    : "# Analyst Self-Improvement Recommendations\n\nProposed by the Analyst when it notices recurring weaknesses. Review, then apply the good ones to prompt.ts or the process.\n";
  const lines = recommendations.map((r) => `- _(from ${r.idea})_ ${r.text}`);
  fs.writeFileSync(
    RECOMMENDATIONS_FILE,
    `${existing.trimEnd()}\n\n## ${date}\n\n${lines.join("\n")}\n`,
  );
}

async function main(): Promise<void> {
  const ideaFiles = findIdeaFiles(IDEAS_DIR);
  if (ideaFiles.length === 0) {
    console.log("No idea files found in ideas/ (README.md is ignored).");
    console.log("Add one markdown file per idea, then run `npm run analyst` again.");
    return;
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ANTHROPIC_API_KEY is not set. Get a key at https://platform.claude.com/");
    process.exitCode = 1;
    return;
  }

  const client = new Anthropic();
  fs.mkdirSync(EXPERIMENTS_DIR, { recursive: true });

  // The lessons file is read once, then kept in memory and re-written after
  // every analysis — so idea N+1 in the same run sees idea N's lessons.
  let lessonsContent = fs.existsSync(LESSONS_FILE)
    ? fs.readFileSync(LESSONS_FILE, "utf8")
    : "# Lessons\n";
  const today = new Date().toISOString().slice(0, 10);

  const startingLessons = parseLessons(lessonsContent).length;
  console.log(
    `Analyst V2: ${ideaFiles.length} idea(s) to investigate, ` +
      `${startingLessons} prior lesson(s) loaded.\n`,
  );

  const entries: AnalysisEntry[] = [];
  const recommendations: { idea: string; text: string }[] = [];

  for (const file of ideaFiles) {
    const name = ideaNameFromFile(file);
    const ideaText = fs.readFileSync(file, "utf8");
    const knowledgeBase = renderKnowledgeBase(parseLessons(lessonsContent));
    const priorAnalyses = summarizePriorAnalyses(name);
    process.stdout.write(`Investigating "${name}" `);

    try {
      const report = await analyzeIdea(
        client,
        buildUserMessage(name, ideaText, knowledgeBase, priorAnalyses),
      );
      const verdict = extractVerdict(report);
      fs.writeFileSync(
        path.join(EXPERIMENTS_DIR, `${name}-analysis.md`),
        reportHeader(file) + report + "\n",
      );
      entries.push({ name, verdict, reportPath: reportRelativePath(name) });

      // Lessons: extract → dedupe → append to LESSONS.md immediately.
      const { lessons: candidates, skipped } = extractCandidateLessons(report);
      const updated = updateLessonsFile(lessonsContent, candidates, today, name);
      lessonsContent = updated.content;
      fs.writeFileSync(LESSONS_FILE, lessonsContent);
      for (const line of skipped) {
        console.warn(`\n  Skipped lesson with unknown category: ${line}`);
      }

      for (const text of extractRecommendations(report)) {
        recommendations.push({ idea: name, text });
      }

      console.log(
        ` done → ${verdict} (${reportRelativePath(name)}), ` +
          `${updated.added.length} new lesson(s)`,
      );
    } catch (err) {
      if (err instanceof Anthropic.APIError) {
        console.error(`\nAPI error ${err.status} on "${name}": ${err.message}`);
      } else {
        console.error(`\nFailed on "${name}":`, err);
      }
      process.exitCode = 1;
    }
  }

  if (entries.length > 0) {
    const existing = fs.existsSync(STATUS_FILE)
      ? fs.readFileSync(STATUS_FILE, "utf8")
      : "# Project Status\n";
    fs.writeFileSync(STATUS_FILE, updateProjectStatus(existing, entries, today));
    console.log(`\nPROJECT_STATUS.md updated (${entries.length} analysis entries).`);

    const totalLessons = parseLessons(lessonsContent).length;
    console.log(
      `LESSONS.md now holds ${totalLessons} lesson(s) ` +
        `(+${totalLessons - startingLessons} this run).`,
    );
  }

  appendRecommendations(recommendations, today);
  if (recommendations.length > 0) {
    console.log(
      `${recommendations.length} self-improvement recommendation(s) → agents/analyst/RECOMMENDATIONS.md`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
